FROM python:3.9

WORKDIR /FYLE

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7755

ENV FLASK_APP=core/server.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=7755"]